[workspace]
resolver = "3"
members = [
    "moonlight-client-simple",
    "moonlight-common",
    "moonlight-common-sys",
    "moonlight-web",
]

[workspace.package]
license = "GPL-3.0-or-later"

[workspace.dependencies]
moonlight-common = { path = "./moonlight-common" }
moonlight-common-sys = { path = "./moonlight-common-sys", features = [
    "vendored",
] }

[workspace.lints.clippy]
too_many_arguments = "allow"
unwrap_used = "warn"
