# Maybe helpful for building
# https://github.com/moonlight-stream/moonlight-qt?tab=readme-ov-file#building
# https://docs.lizardbyte.dev/projects/sunshine/latest/md_docs_2building.html

[target.x86_64-pc-windows-gnu]
dockerfile = "./Cross/Windows"
