# Docs: https://jhugman.github.io/uniffi-bindgen-react-native/reference/config-yaml.html

rust:
  repo: https://github.com/MrCreativ3001/moonlight-common-rust.git
  branch: 75ff0e67159445074bafc018f9855b3a6a0c17b2
  manifestPath: bindings/Cargo.toml

web:
  entrypoint: web/uniffi/entry.ts
  tsBindings: web/uniffi
  defaultFeatures: false
  features: ["web"]
  manifestPatchFile: ./Cargo.wasm.toml
