# Docs: https://jhugman.github.io/uniffi-bindgen-react-native/reference/config-yaml.html

rust:
  repo: https://github.com/MrCreativ3001/moonlight-common-rust.git
  branch: 62e088ee39b5f695869e567d3ed066ab19f9e482
  manifestPath: bindings/Cargo.toml

web:
  entrypoint: web/uniffi/entry.ts
  tsBindings: web/uniffi
  defaultFeatures: false
  features: ["web"]
  manifestPatchFile: ./Cargo.wasm.toml
