[package]
name = "moonlight-client-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
moonlight-common = { workspace = true }
tokio = { version = "1.46.1", features = ["full"] }

rcgen = "0.14.3"
pem = "3.0.5"

gstreamer = "0.24.0"
gstreamer-app = "0.24.0"
