[package]
name = "moonlight-client-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
moonlight-common = { workspace = true }
tokio = { version = "1.46.1", features = ["full"] }

[lints]
workspace = true
