[package]
name = "moonlight-common"
version = "0.1.0"
edition = "2024"

[dependencies]
moonlight-common-sys = { workspace = true }

url = "2.5.4"
reqwest = "0.12.22"
roxmltree = "0.20.0"
uuid = { version = "1.17.0", features = ["v4"] }
thiserror = "2.0.12"
form_urlencoded = "1.2.1"
hex = "0.4.3"

# Crypto
sha2 = { version = "0.10.9", optional = true }
sha1 = { version = "0.10.6", optional = true }

# High
tokio = { version = "1.46.1", default-features = false, features = [
    "rt",
], optional = true }

[features]
default = ["high", "dep:tokio"]

# High level api
high = ["crypto"]

# Crypto
crypto = ["moonlight-common-sys/crypto", "dep:sha1", "dep:sha2"]

[lints]
workspace = true
