[package]
name = "moonlight-common"
version = "0.1.0"
edition = "2024"

[dependencies]
moonlight-common-sys = { workspace = true }

url = "2.5.4"
reqwest = "0.12.22"
roxmltree = "0.20.0"
uuid = { version = "1.17.0", features = ["v4"] }
thiserror = "2.0.12"
form_urlencoded = "1.2.1"
hex = "0.4.3"

# High
tokio = { version = "1.46.1", default-features = false, features = [
    "rt",
], optional = true }
sha2 = { version = "0.10.9", optional = true }
sha1 = { version = "0.10.6", optional = true }
# TODO: aes / block-modes: replace with non deprecated crate
aes = { version = "0.7.5", optional = true }
block-modes = { version = "0.8.1", optional = true }
rsa = { version = "0.9.8", optional = true }
der = { version = "0.7.10", features = ["pem"] }
x509-parser = { version = "0.17.0", optional = true }
pem = { version = "3.0.5", optional = true }

[features]
default = ["high"]

# High level api
high = [
    "crypto",
    "dep:tokio",
    "dep:sha1",
    "dep:sha2",
    "dep:aes",
    "dep:rsa",
    "dep:block-modes",
    "dep:x509-parser",
    "dep:pem",
]

# Crypto
crypto = ["moonlight-common-sys/crypto"]

[lints]
workspace = true
