[package]
name = "moonlight-common"
version = "0.1.0"
edition = "2024"

[dependencies]
moonlight-common-sys = { workspace = true }

thiserror = "2.0.12"

# Network
url = { version = "2.5.4", optional = true }
reqwest = { version = "0.12.22", optional = true }
roxmltree = { version = "0.20.0", optional = true }
uuid = { version = "1.17.0", features = ["v4"], optional = true }
form_urlencoded = { version = "1.2.1", optional = true }
hex = { version = "0.4.3", optional = true }

# High
tokio = { version = "1.46.1", default-features = false, features = [
    "rt",
], optional = true }
sha2 = { version = "0.10.9", features = ["oid"], optional = true }
sha1 = { version = "0.10.6", optional = true }
# TODO: aes / block-modes: replace with non deprecated crate
aes = { version = "0.7.5", optional = true }
block-modes = { version = "0.8.1", optional = true }
# TODO: remove dependencies by looking for overlap in features
rsa = { version = "0.9.8", optional = true }
der = { version = "0.7.10", features = ["pem"] }
x509-parser = { version = "0.17.0", optional = true }
nom = { version = "7.1.3", optional = true }
pem = { version = "3.0.5", optional = true }
rcgen = { version = "0.14.3", features = ["aws_lc_rs"], optional = true }

[features]
default = ["high"]

# High level api
high = [
    "network",
    "crypto",
    "dep:tokio",
    "dep:sha1",
    "dep:sha2",
    "dep:aes",
    "dep:rsa",
    "dep:block-modes",
    "dep:x509-parser",
    "dep:nom",
    "dep:pem",
    "dep:rcgen",
    "reqwest/rustls-tls",
]

# Crypto
crypto = ["moonlight-common-sys/crypto"]

# Network
network = [
    "dep:tokio",
    "dep:url",
    "dep:reqwest",
    "dep:roxmltree",
    "dep:uuid",
    "dep:form_urlencoded",
    "dep:hex",
]

[lints]
workspace = true
